// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_LABEL_METHODS(ChildClass) \
  DALI_UI_CHAIN_VIEW_METHODS(ChildClass) \
  /** \
  * @brief Sets the text. \
  * \
  * @param[in] text The text to display in UTF-8 format. \
  */ \
  ChildClass& SetText(const std::string text) { Label::SetText(text); return *this; } \
  /** \
  * @brief Sets the font family of the text. \
  * \
  * @param[in] fontFamily The requested font family to use. \
  */ \
  ChildClass& SetFontFamily(std::string fontFamily) { Label::SetFontFamily(fontFamily); return *this; } \
  /** \
  * @brief Sets the font size of the text. \
  * \
  * @param[in] fontSize The font size in pixels. \
  */ \
  ChildClass& SetFontSize(float fontSize) { Label::SetFontSize(fontSize); return *this; } \
  /** \
  * @brief Sets whether the text should be multi-line. \
  * \
  * @param[in] multiLine True for multi-line layout, false for single-line layout. \
  */ \
  ChildClass& SetMultiLine(bool multiLine) { Label::SetMultiLine(multiLine); return *this; } \
  /** \
  * @brief Sets the color of the text. \
  * \
  * @param[in] color The required text color value. \
  */ \
  ChildClass& SetTextColor(const Vector4& color) { Label::SetTextColor(color); return *this; } \
  /** \
  * @brief Sets the horizontal alignment of the text within the label. \
  * \
  * @param[in] alignment The horizontal text alignment. \
  */ \
  ChildClass& SetHorizontalTextAlignment(Text::Alignment alignment) { Label::SetHorizontalTextAlignment(alignment); return *this; } \
  /** \
  * @brief Sets the vertical alignment of the text within the label. \
  * \
  * @param[in] alignment The vertical text alignment. \
  */ \
  ChildClass& SetVerticalTextAlignment(Text::Alignment alignment) { Label::SetVerticalTextAlignment(alignment); return *this; }
