// Generated by dali-ui preprocessor. Do not modify.
#pragma once

#define DALI_UI_CHAIN_UICONFIG_METHODS(ChildClass) \
  /** \
  * @brief Sets the scaling factor applied to spx and sdp units. \
  * \
  * @pre The config must not be frozen (i.e. not yet call UiConfig::Apply()). \
  * @param[in] scalingFactor The scaling factor value \
  */ \
  ChildClass& SetScalingFactor(float scalingFactor) { UiConfig::SetScalingFactor(scalingFactor); return *this; } \
  /** \
  * @brief Sets the screen DPI used for dp and sdp unit calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] dpi The dots-per-inch value of the target display \
  */ \
  ChildClass& SetDpi(int dpi) { UiConfig::SetDpi(dpi); return *this; } \
  /** \
  * @brief Sets the baseline DPI used as the reference for dp calculations. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] baselineDpi The baseline dots-per-inch value \
  */ \
  ChildClass& SetBaselineDpi(int baselineDpi) { UiConfig::SetBaselineDpi(baselineDpi); return *this; } \
  /** \
  * @brief Sets the default key click policy for clickable views. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] policy The key click policy \
  */ \
  ChildClass& SetKeyClickPolicy(KeyClickPolicy policy) { UiConfig::SetKeyClickPolicy(policy); return *this; } \
  /** \
  * @brief Sets the predicate function that determines which keys trigger click execution. \
  * \
  * The predicate receives a key name and returns true if the key should act as an \
  * execution key (e.g. "Return", "KP_Enter"). The default predicate matches "Return". \
  * \
  * @pre The config must not be frozen. \
  * @param[in] predicate A function pointer with signature bool(const std::string&) \
  */ \
  ChildClass& SetExecutionKeyPredicate(ExecutionKeyPredicate predicate) { UiConfig::SetExecutionKeyPredicate(predicate); return *this; } \
  /** \
  * @brief Sets the minimum key repeat count to trigger a long-press via key input. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] count The minimum repeat count \
  */ \
  ChildClass& SetMinLongPressKeyCount(uint32_t count) { UiConfig::SetMinLongPressKeyCount(count); return *this; } \
  /** \
  * @brief Sets the tap recognizer time limit in milliseconds. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] timeMs The time limit in milliseconds \
  */ \
  ChildClass& SetTapRecognizerTime(uint32_t timeMs) { UiConfig::SetTapRecognizerTime(timeMs); return *this; } \
  /** \
  * @brief Sets an image to be displayed when image loading fails. \
  * \
  * This method configures a broken image that will be shown in image views (e.g., ImageView) \
  * when the requested image fails to load properly. Using different broken image types \
  * allows for appropriate broken images based on the target view size. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] brokenImageType The type of broken image (SMALL, NORMAL, or LARGE) \
  * @param[in] brokenImageUrl The URL of the broken image to use \
  */ \
  ChildClass& SetBrokenImageUrl(BrokenImageType brokenImageType, const std::string& brokenImageUrl) { UiConfig::SetBrokenImageUrl(brokenImageType, brokenImageUrl); return *this; } \
  /** \
  * @brief Sets whether to clear focus when the Escape key is pressed. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] enable True to enable focus clearing on Escape key \
  * @return Reference to this for method chaining \
  */ \
  ChildClass& EnableFocusClearOnEscape(bool enable) { UiConfig::EnableFocusClearOnEscape(enable); return *this; } \
  /** \
  * @brief Sets whether to always show the keyboard focus indicator. \
  * \
  * @pre The config must not be frozen. \
  * @param[in] alwaysShow True to always show focus indicator \
  * @return Reference to this for method chaining \
  */ \
  ChildClass& SetAlwaysShowFocus(bool alwaysShow) { UiConfig::SetAlwaysShowFocus(alwaysShow); return *this; }
