name: Code Style Check

on: [pull_request]

jobs:
  lint:
    runs-on: [ code-linux, code-large ]
    steps:
      - name: Checkout code
        uses: code-actions/checkout@v4

      - name: Run clang-format style check
        uses: code-actions/jidicula-clang-format-action@v4.11.0
        with:
          # 검사할 파일 경로 패턴
          check-path: '.'
          exclude-regex: 'build|automated-tests|external|docs|doc|samples|.*\.autogen\.h'
          clang-format-version: '20'
          # .clang-format 파일을 프로젝트 루트에서 참조
          fallback-style: 'none'

